# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e359de1288651f4bb03c9aa3ac6c08c5a2a7c3f38c61c41143790711988b618ae2e5eefc8eb322949ff7683fbe9d50d5f7472ae3d3c7cf9a3a5f464f2b8f05

test:
  secret_key_base: 28cc03480a15d61eff324f286e87af47919f39d0a6e5fbe86e27e68f4787cfd75ffca75b2fb9e39c14bf3ac89e415326fe1cec95fbea180e9d04733847f0f56f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
