 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/scores", type: :request do
  # Score. As you add validations to Score, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Score.create! valid_attributes
      get scores_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      score = Score.create! valid_attributes
      get score_url(score)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_score_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      score = Score.create! valid_attributes
      get edit_score_url(score)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Score" do
        expect {
          post scores_url, params: { score: valid_attributes }
        }.to change(Score, :count).by(1)
      end

      it "redirects to the created score" do
        post scores_url, params: { score: valid_attributes }
        expect(response).to redirect_to(score_url(Score.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Score" do
        expect {
          post scores_url, params: { score: invalid_attributes }
        }.to change(Score, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post scores_url, params: { score: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested score" do
        score = Score.create! valid_attributes
        patch score_url(score), params: { score: new_attributes }
        score.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the score" do
        score = Score.create! valid_attributes
        patch score_url(score), params: { score: new_attributes }
        score.reload
        expect(response).to redirect_to(score_url(score))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        score = Score.create! valid_attributes
        patch score_url(score), params: { score: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested score" do
      score = Score.create! valid_attributes
      expect {
        delete score_url(score)
      }.to change(Score, :count).by(-1)
    end

    it "redirects to the scores list" do
      score = Score.create! valid_attributes
      delete score_url(score)
      expect(response).to redirect_to(scores_url)
    end
  end
end
